version=0.1.0-SNAPSHOT
group=eu.holistit
artifactId=holistIT-auth-gateway-spring-cloud-starter
githubUrl=https://github.com/gflachs/holistIT-auth-gateway-spring-cloud-starter
githubSshUrl=git@github.com:gflachs/holistIT-auth-gateway-spring-cloud-starter.git
packageUrl=https://maven.pkg.github.com/gflachs/holistIT-auth-gateway-spring-cloud-starter
description=Spring Cloud Starter for Auth Gateway by HolistIT
packageName=eu.holistit.package.holistIT-auth-gateway-spring-cloud-starter