version=0.1.0-SNAPSHOT
group=eu.holistit
artifactId=holistit-java-package-template
githubUrl=
githubSshUrl=
packageUrl=https://maven.pkg.github.com/gflachs/holistit-java-package-template
description=Template for Java packages at holistIT. Provides a standard structure and configuration for Java projects, including build settings, dependencies, and publishing configuration.
packageName=eu.holistit.package.template